version: '3.6'

services:
  vm-console-ui:
    image: ${REGISTRY_URL}${NAMESPACE}${REPO}vm-console-ui:${VM_CONSOLE_UI_TAG}
    deploy:
      replicas: 1
      labels:
        - 'traefik.enable=true'
        - 'traefik.port=80'
        - 'traefik.docker.network=traefik-net'
        - 'traefik.console.frontend.rule=Host:vm-console.${DOMAIN}'
        - 'traefik.console.frontend.entrypoints=https'
        - 'traefik.console.backend=vm-console-ui'
    networks:
      - traefik-net
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'
    configs:
      - source: vm-console-ui-settings
        target: /usr/share/nginx/html/assets/config/settings.env.json
networks:
  utilities:
    external: true
  traefik-net:
    external: true

volumes:
  vcenter-certs:
    driver_opts:
      type: 'nfs'
      o: 'addr=${NFS_SERVER},nolock,soft,rw'
      device: ':/mnt/data/certificates/vcenter/lin'
  sei-ca:
    driver_opts:
      type: 'nfs'
      o: 'addr=${NFS_SERVER},nolock,soft,rw'
      device: ':/mnt/data/certificates'

configs:
  vm-console-ui-settings:
    file: ./vm-console-ui-settings.json

secrets:
  anvil-private-key:
    external: true
  anvil-certificate:
    external: true
