version: "3.6"

services:
  player-api:
    image: ${REGISTRY_URL}${NAMESPACE}${REPO}player-api:${PLAYER_API_TAG}
    entrypoint: bash -c "update-ca-certificates && dotnet S3.Player.Api.dll"
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.backend=player-api"
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:player-api.${DOMAIN}"
        - "traefik.frontend.entrypoints=http,https"
    networks:
      - utilities
      - traefik-net
    volumes:
      - sei-ca:/usr/local/share/ca-certificates
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    configs: 
      - source: player-api-settings
        target: /app/appsettings.Production.json
    
  player-ui:
    image: ${REGISTRY_URL}${NAMESPACE}${REPO}player-ui:${PLAYER_UI_TAG}
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.backend=player-ui"
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:player.${DOMAIN}"
        - "traefik.frontend.entrypoints=http,https"
    networks:
      - traefik-net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    configs:
      - source: player-ui-settings
        target: /usr/share/nginx/html/assets/config/settings.env.json
volumes:
  sei-ca:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SERVER},nolock,soft,rw"
      device: ":${NFS_BASE_PATH}certificates/sei-ca"
networks:
  utilities:
    external: true
  traefik-net:
    external: true

configs:
  player-api-settings:
    file: ./player-api-settings.json
  player-ui-settings:
    file: ./player-ui-settings.json
